# https://github.com/KeithGalli/pycon2020

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

class_names=['BOOKS', 'CLOTHING']
X_train = ['i love the book', 'this is a great book', 'the fit is great', 'i love the shoes']
y_train = [0, 0, 1, 1]
vectorizer = CountVectorizer(ngram_range=(1,2))

X_train_vectors = vectorizer.fit_transform(X_train)
print(vectorizer.get_feature_names_out())
for i in range(4):
  print(X_train_vectors[i].toarray())

['book' 'fit' 'fit is' 'great' 'great book' 'is' 'is great' 'love'
 'love the' 'shoes' 'the' 'the book' 'the fit' 'the shoes' 'this'
 'this is']
[[1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0]]
[[1 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1]]
[[0 1 1 1 0 1 1 0 0 0 1 0 1 0 0 0]]
[[0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0]]


In [ ]:
from sklearn import svm

model = svm.SVC(kernel='linear')
model.fit(X_train_vectors, y_train)

SVC(kernel='linear')

In [ ]:
X_test = vectorizer.transform(['I like the book', 'Shoes are cool', 'Where did you get that book','The love for the book', 'Fit the book on the shelf', 'Nice fit bro', 'I love the fit of that book in my life', 'I love the books'])
y_test = model.predict(X_test)
for pred in y_test:
  print(class_names[pred])

BOOKS
CLOTHING
BOOKS
BOOKS
BOOKS
CLOTHING
BOOKS
CLOTHING


In [ ]:
import spacy
#!python -m spacy download en_core_web_md

/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 12.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
nlp = spacy.load('en_core_web_md')

/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(


In [ ]:
docs = []
X_train = ['i love the book', 'this is a great book', 'the fit is great', 'i love the shoes']
y_train = [0, 0, 1, 1]
for text in X_train:
  docs.append(nlp(text))
X_train_word_vectors = [x.vector for x in docs]

In [ ]:
model_1 = svm.SVC(kernel='linear')

model_1.fit(X_train_word_vectors, y_train)

SVC(kernel='linear')

In [ ]:
X_word_test = ['I like the book', 'Shoes are cool', 'Where did you get that book','The love for the book', 'Fit the book on the shelf', 'Nice fit bro', 'I love the fit of that book in my life', 'I love the books',
               'I love the story', 'The library is so nice', 'I like that red scarf', 'Those earrings are ugly', 'I want to read that']
test_docs = [nlp(text) for text in X_word_test]
X_test_word_vectors = [x.vector for x in test_docs]

y_pred = model_1.predict(X_test_word_vectors)
for i in range(len(y_pred)):
  print(X_word_test[i], class_names[y_pred[i]])

I like the book BOOKS
Shoes are cool CLOTHING
Where did you get that book BOOKS
The love for the book BOOKS
Fit the book on the shelf BOOKS
Nice fit bro CLOTHING
I love the fit of that book in my life BOOKS
I love the books BOOKS
I love the story BOOKS
The library is so nice CLOTHING
I like that red scarf CLOTHING
Those earrings are ugly CLOTHING
I want to read that CLOTHING


In [ ]:
import re #regex

regexp = re.compile('ab[\S]*cd')  # ab; [^\s] = not \s = not whitespace = [\S] ; * = at least 0 times; cd => starts with ab, at least 0 chars that are not whitespace(' '); cd

phrases = ['abcd', 'xxx', 'abdofiofcd', 'ab cd', 'the silly abbccd amogus']
matches = []
for phrase in phrases:
  if re.match(regexp, phrase):
    matches.append(phrase)
print(matches)
matches2 = []
for phrase in phrases:
  if re.search(regexp, phrase):
    matches2.append(phrase)
print(matches2)

['abcd', 'abdofiofcd']
['abcd', 'abdofiofcd', 'the silly abbccd amogus']


In [ ]:
regexp = re.compile(r'hat|book|cook')
regexp2 = re.compile(r'\bhat\b|\bbook\b|\bcook\b') #\b = word boundary (requires that its a word of itself)
phrases = ['The rat stole my hat.', 'Nice book mate','Cook for me','I booked the apartment', 'What is wrong with you']
matches = []
matches2 = []
for phrase in phrases:
  if re.search(regexp, phrase):
    matches.append(phrase)
  if re.search(regexp2, phrase):
    matches2.append(phrase)
print(matches)
print(matches2)

['The rat stole my hat.', 'Nice book mate', 'I booked the apartment', 'What is wrong with you']
['The rat stole my hat.', 'Nice book mate']


In [ ]:
import nltk

nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

phrase = "I'm really interested in those books of yours. From where have you bought them?"

words = word_tokenize(phrase)
print(f"Words: {words}")
stemmed_words = []
for word in words:
  stemmed_words.append(stemmer.stem(word))
print(f"Stemmed words: {stemmed_words}")

Words: ['I', "'m", 'really', 'interested', 'in', 'those', 'books', 'of', 'yours', '.', 'From', 'where', 'have', 'you', 'bought', 'them', '?']
Stemmed words: ['i', "'m", 'realli', 'interest', 'in', 'those', 'book', 'of', 'your', '.', 'from', 'where', 'have', 'you', 'bought', 'them', '?']


In [ ]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

lemmatized_words = []
for word in words:
  lemmatized_words.append(lemmatizer.lemmatize(word))
print(phrase)
print(f"Lemmatized words: {lemmatized_words}")

I'm really interested in those books of yours. From where have you bought them?
Lemmatized words: ['I', "'m", 'really', 'interested', 'in', 'those', 'book', 'of', 'yours', '.', 'From', 'where', 'have', 'you', 'bought', 'them', '?']


In [ ]:
from nltk.corpus import stopwords

stop_words = stopwords.words('english')
print(stop_words)
stripped_phrase = []
for word in words:
  if word not in stop_words:
    stripped_phrase.append(word)
print(stripped_phrase) #I was not removed because uppercase. What if we first stem?

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [ ]:
stripped_stemmed_phrase = []
for word in stemmed_words:
  if word not in stop_words:
    stripped_stemmed_phrase.append(word)
print(stripped_stemmed_phrase)

["'m", 'realli', 'interest', 'book', '.', 'bought', '?']


In [ ]:
from textblob import TextBlob
#nltk.download('averaged_perceptron_tagger')

phrase = 'Thet book was absolutuly horible!'
tb_phrase = TextBlob(phrase)
tb_phrase = tb_phrase.correct()
print(f"Phrase: {phrase}\n")
print(f"Corrected: {tb_phrase}\n")
print(f"Tags: {tb_phrase.tags}\n") #DT = determniner, NN = singular noun etc
print(f"Sentiment: {tb_phrase.sentiment}") #polarity = negative or positive

Phrase: Thet book was absolutuly horible!

Corrected: The book was absolutely horrible!

Tags: [('The', 'DT'), ('book', 'NN'), ('was', 'VBD'), ('absolutely', 'RB'), ('horrible', 'JJ')]

Sentiment: Sentiment(polarity=-1.0, subjectivity=1.0)
